version: '3'
services:
  
  product:
    depends_on: 
      - product-database 
    image: ecomm/product
    build: product # docker build ./product -t pagonxt/product
    entrypoint: 'npm run start:dev'
    volumes:
      - ./product:/app
    ports:
      - 3000:3000
  
  product-database:
    image: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: rXV4PShcYEhm9pyy/BONu8/urLbm4WCP
      MYSQL_DATABASE: products
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpass
    ports:
      - 3307:3306 #porta 3306 já esta ocupada na máquina. 

  account:
    depends_on:
      - account-database
    image: pagonxt/account
    build: account # docker build ./account -t ecomm/account
    entrypoint: 'npm run start:dev'
    volumes:
      - ./account:/app
    ports:
      - 3001:3000
  
  account-database:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: accounts
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopass
    ports:
      - 27017:27017
