FROM node:18
WORKDIR /app
COPY pacote.json package-lock.json /app/
RUN npm install
COPY . .
EXPOSE 3000
ENTRYPOINT ["npm", "start"]

#FROM: Seleciona a imagem que iremos utilizar. No caso o node na versão.
#WORKDIR: É um diretório gerado dentro do Docker onde nossa aplicação será mantida.
#COPY: Adiciona uma pasta para o diretório do Docker.
#RUN: Executa comandos dentro do container.
#COPY . .:Adiciona uma pasta para o diretório do Docker
#EXPOSE: Expõe uma porta para o container.
#ENTRYPOINT: É o ponto de entrada quando você iniciar o container, ou seja, geralmente definimos no ENTRYPOINT o comando ou script que chama o processo responsável pela execução do container e que manterá o container vivo.
#CDM: Executa comandos após a criação do container.

# rodar no terminal => docker build -t eccom/account .
# rodar no terminal => docker image ls / pegar o id da image
# rodar no termial => docker run <id da image>
