openapi: 3.0.3
info:
  version: 1.0.0
  title: Accounts API
  description: API Restful que lida com contas
  contact:
    name: Suporte a Devs
    url: 'https://www.example.com.br'
    email: devs@example.com.br
servers:
  - url: 'http://localhost:3001'
    description: Server 1
paths:
  /accounts:
    summary: Cria conta
    description: 'Cria uma conta no banco de dados de acordo com as informações fornecidas'
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAccountRequest'
      responses:
        201:
          description: Conta criada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountResponse'
        400:
          description: Conta não criada
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /tokens:
    summary: Cria um token de conta
    description: 'Cria um token de conta com é informado e-mail e senha'
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email: 
                  type: string
                password:
                  type: string
      responses:
        201:
          description: Conta de token criada
          content:
            application/json:
              schema:
                type: object
                properties: 
                  token:
                    type: string
        401:
          description: Erro com dados da conta
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:  
                    type: string

components:
  schemas:
    CreateAccountRequest:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
    AccountResponse:
      type: object
      properties:
        id: 
          type: string
        name:
          type: string
        email:
          type: string
        createdDate:
          type: string
