openapi: 3.0.3
info:
  version: 1.0.0
  title: Accounts API
  description: Restful API that deals with Accounts
  contact:
    name: Suporte a Devs
    url: 'https://www.example.com.br'
    email: devs@example.com.br
servers:
  - url: 'http://localhost:3001'
    description: Server 1
paths:
  /accounts:
    summary: cria conta
    description: 'Cria uma conta no banco de dados de acordo com as informações fornecidas'
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountData'
      responses:
        201:
          description: conta criada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatedAccountData'

components:
  schemas:
    AccountData:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
    CreatedAccountData:
      type: object
      properties:
        id: 
          type: string
        name:
          type: string
        email:
          type: string
        createdDate:
          type: string
